dubbo:
  application:
    name: butterfly_server
  registry:
    address: 127.0.0.1:2181
    protocol: zookeeper
  protocol:
    name: dubbo
    port: 20997
#  registry:
#    address: zookeeper://127.0.0.1:2181
